# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f ~/.profile ]; then
  source ~/.profile
fi

# User specific aliases and functions
export PATH="~/.yodo:$PATH"
export VAGRANT_DEFAULT_PROVIDER="virtualbox"
